[config]
schemaVersion = "0.0.1"

[package]
namespace = "Caioreix"
name = "PluginName"
versionNumber = "0.0.0"
description = "My first plugin."
websiteUrl = "https://github.com/caioreix/PluginName"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = []

[publish.categories]
