name: Build Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    if: github.repository != 'caioreix/bepinex-template'
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - uses: caioreix/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: .nuspec

      - name: Check for Tag
        run: |
          TAG=${{steps.get-version.outputs.version}}

          echo "VERSION=$TAG" >> $GITHUB_ENV
          echo "version=$TAG" >> $GITHUB_OUTPUT

      - name: Check if release already exists
        id: check_release
        run: |
          if gh release view "v${{ env.VERSION }}" &> /dev/null; then
            echo "::error::Release v${{ env.VERSION }} already exists."
            exit 1
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (Release)
        run: nuget pack .nuspec -NoDefaultExcludes -OutputDirectory ./dist

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist

      - name: Create GitHub Release
        if: steps.check_release.outputs.exists == 'false' && github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: ./dist/*
          fail_on_unmatched_files: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
